version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  node:
    image: node-mysql-app
    container_name: node
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret_password
      MYSQL_DB: app_db
      PORT: 3000
    restart: always
    ports:
      - 8081:3000
volumes:
  dbdata:
