version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - '6033:3306'
    volumes:
      - dbdata:/var/lib/mysql
  node:
    image: node-mysql-app
    container_name: node
    links:
      - db
    environment:
      MYSQL_HOST: db
      PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret_password
      MYSQL_DB: app_db
    restart: always
    ports:
      - 8081:3306
volumes:
  dbdata:
